### ISSUE TITLE
Failed to activate the atom-html-preview package

### ISSUE THREAD

**Issue by danieldizzy** [webBoxio/atom-html-preview#107]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.19

### Stack Trace

Failed to activate the atom-html-preview package

```
At ENOENT: no such file or directory, lstat '/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu'

Error: ENOENT: no such file or directory, lstat '/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu'
    at Error (native)
    at fs.lstatSync (fs.js:887:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:229:16)
    at realpathSync (fs.js:1532:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:314:24)
    at toRealPath (module.js:113:13)
    at Function.Module._findPath (module.js:153:20)
    at Module._resolveFilename (module.js:336:25)
    at Function.Module._resolveFilename (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:53:23)
    at Object.<anonymous> (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:12:41)
    at Object.<anonymous> (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:361:4)
    at Module._compile (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:18:28)
    at Object.<anonymous> (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/danieldizzy/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:3:25)
    at Object.<anonymous> (/Users/danieldizzy/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:1:1)
    at Module._compile (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/danieldizzy/Library/Application Support/com.github.atom.ShipIt/update.rKic6Hu/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  },
  "atom-html-preview": {
    "triggerOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by augierakow** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-html-preview](https://github.com/harmsk/atom-html-preview) package 0.2.6


### Stack Trace

Failed to activate the atom-html-preview package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:/ProgramData/rakow/atom/app-1.46.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/csslint/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at /packages/csslint/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at /packages/csslint/node_modules/atom-space-pen-views/lib/main.js:24:3)
    at Module.get_Module._compile (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-html-preview/lib/atom-html-preview-view.coffee:3:25)
    at /packages/atom-html-preview/lib/atom-html-preview-view.coffee:1:1)
    at /packages/atom-html-preview/lib/atom-html-preview-view.coffee:1:1)
    at Module.get_Module._compile (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-html-preview/lib/atom-html-preview.coffee:4:25)
    at /packages/atom-html-preview/lib/atom-html-preview.coffee:1:1)
    at /packages/atom-html-preview/lib/atom-html-preview.coffee:1:1)
    at Module.get_Module._compile (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:/ProgramData/rakow/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
```

### Commands

```
  2x -6:20.5.0 application:open-folder (div.package-detail)
     -4:10 application:open-file (div.package-detail)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by kavinGurusamy** [comment]
apm install atom-html-preview

does not work in atom
