### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by JeancarloPerez** [webBoxio/atom-html-preview#46]
I have this error when I try to see the preview of the html:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.6

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:128

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:904:15)
  at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:556:26)
  at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.renderHTMLCode (/Users/jeancarloperez/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:95:76)
  at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.renderHTML (/Users/jeancarloperez/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:92:8)
  at /Users/jeancarloperez/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:54:25
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:516:49
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -3:31.5 project-manager:toggle (atom-text-editor.editor)
     -3:30.6 core:confirm (atom-text-editor.editor.mini)
  2x -3:22.2 core:paste (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -0:37.0 grammar-selector:show (atom-text-editor.editor)
     -0:36.0 core:confirm (atom-text-editor.editor.mini)
  5x -0:28.1 core:copy (atom-text-editor.editor)
     -0:27.2 application:new-file (atom-text-editor.editor)
     -0:26.8 core:paste (atom-text-editor.editor)
     -0:26.5 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:26.5 editor:newline (atom-text-editor.editor)
     -0:25.4 core:undo (atom-text-editor.editor)
     -0:24.2 grammar-selector:show (atom-text-editor.editor)
     -0:22.9 core:confirm (atom-text-editor.editor.mini)
  2x -0:20.8 find-and-replace:show (atom-text-editor.editor)
  2x -0:11.5 core:move-left (atom-text-editor.editor.mini)
     -0:01.1 atom-html-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
emmet, v2.3.6
file-icons, v1.5.3
minimap, v4.7.5
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by deniss-s** [comment]
Same error.
**System**: Linux Fedora 21 x84_64
**Atom version**: 0.194.0
**Thrown From**: atom-html-preview package, v0.1.6

**Comment by liridoni** [comment]
is there a work around for this?

**Comment by darol100** [comment]
I can confirm that what @liridoni "you have to save the document first. Then run the preview" would work.

**Comment by JeancarloPerez** [comment]
yes that works for me!

**Comment by calebegg** [comment]
It would be nice to have a more clear error message than just a link to this bug.

**Comment by JeancarloPerez** [comment]
The solution of @liridoni  help me. Thanks.

**Comment by calebegg** [comment]
I'm saying that I think this bug should be re-opened because it's annoying to have to come here to find out how to fix it. Even if there's a solution for you, it's still a bug.

**Comment by yckart** [comment]
Yap, I agree to @calebegg, this error still exists!
