### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by kamalh16** [webBoxio/atom-html-preview#67]
[Enter steps to reproduce below:]

1. Open a project using project manager. Split pane to the right, preview 3 html files onto right pane.
2. Open new Atom window, move previews to the new window. (errors pops up here)

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.11

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of null

```
At /Users/khamoud/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:40

TypeError: Cannot read property 'dispose' of null
  at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.destroy (/Users/khamoud/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:40:15)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:468:18)
  at TabBarView.module.exports.TabBarView.onDropOnOtherWindow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:595:21)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "autocomplete-html"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
angularjs, v0.3.0
atom-html-preview, v0.1.11
atom-material-syntax, v0.2.3
atom-ternjs, v0.7.2
autoclose-html, v0.19.0
autocomplete-clang, v0.8.7
browser-plus, v0.0.34
color-picker, v2.0.11
docblockr, v0.7.3
editor-stats, v0.17.0
emmet, v2.3.12
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.5.1
linter-bootlint, v0.0.6
linter-clang, v3.2.1
linter-csslint, v1.0.5
linter-htmlhint, v0.1.1
linter-javac, v1.2.0
minimap, v4.13.3
minimap-highlight-selected, v4.3.0
pigments, v0.15.0
project-manager, v2.5.1
save-session, v0.15.7
set-syntax, v0.3.0
seti-icons, v0.4.5
seti-ui, v0.8.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by evoevodin** [comment]
The same for me:
__Operation System__: OpenSuse 13.2
__Atom version__: 1.3.1
__Thrown From__: atom-html-preview package, v0.1.11

**Comment by colonelpopcorn** [comment]
I was able to reproduce the bug by doing the following

1. Open HTML preview of an HTML file
2. Close atom
3. Relaunch atom

After relaunching the HTML preview is empty and closing the tab will throw the error.

**Comment by aboutandre** [comment]
@colonelpopcorn I second that

**Comment by robinonsay** [comment]
Same

**Comment by uixiaoyougit** [comment]
Same
