### ISSUE TITLE
Uncaught TypeError: atom.workspace.open(...).done is not a function

### ISSUE THREAD

**Issue by bennyp123** [webBoxio/atom-html-preview#76]
[Enter steps to reproduce below:]

1. paste html code without html or body tags
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.13

### Stack Trace

Uncaught TypeError: atom.workspace.open(...).done is not a function

```
At /Users/bennyp/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:52

TypeError: atom.workspace.open(...).done is not a function
  at Object.module.exports.toggle (/Users/bennyp/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:52:68)
  at atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle (/Users/bennyp/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:20:92)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -4:01.5.0 remote-ftp:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:44.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:28.2.0 core:close (atom-text-editor.editor.is-focused)
     -0:23.8.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:22.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:22.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.5.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:20.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:17.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.4.0 atom-html-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "SFTP-deployment",
      "remote-edit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.10
atom-html-preview, v0.1.13
minimap, v4.16.0
pigments, v0.18.1
recent-projects, v0.9.5

# Dev
No dev packages
```

**Comment by kpfromer** [comment]
Look at what I said on this [issue](https://github.com/Chris911/Ask-Stack-Atom/issues/31).
