### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by sedelblut** [webBoxio/atom-html-preview#78]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.13

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
    at global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at Promise.done (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1023:5)
    at Object.module.exports.toggle (/Users/sedelblut/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:52:68)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-html-preview:toggle (/Users/sedelblut/.atom/packages/atom-html-preview/lib/atom-html-preview.coffee:20:92)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:984:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
     -0:02.0 atom-html-preview:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
color-picker, v2.0.13
file-icons, v1.6.11
linter, v1.10.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-markdown, v1.2.1
minimap, v4.16.0
nuclide-flow, v0.0.32
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by feralCode** [comment]
node version?

**Comment by sedelblut** [comment]
Node 4.2.2

**Comment by phaibin** [comment]
same issue, 1.2.1 doesn't fix that.

**Comment by phaibin** [comment]
Disable nuclide-flow will fix this.
