### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of null

### ISSUE THREAD

**Issue by ihyildiz** [webBoxio/atom-html-preview#91]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-html-preview](https://github.com/webBoxio/atom-html-preview) package, v0.1.13

### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:829

TypeError: Cannot read property 'getTitle' of null
    at AtomHtmlPreviewView.module.exports.AtomHtmlPreviewView.save (/Users/iyildiz/.atom/packages/atom-html-preview/lib/atom-html-preview-view.coffee:98:49)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:534:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:517:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:643:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:13.8.0 window:focus-next-pane (div.atom-html-preview.native-key-bindings)
  3x -0:10.5.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:03.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13

# Dev
No dev packages
```

**Comment by ZombieHippie** [comment]
Would you provide information about the files that you had open, and their paths?
I believe these are the lines which you are seeing issue with:
```coffee

  save: (callback) ->
    # Temp file path
    outPath = path.resolve path.join(os.tmpdir(), @editor.getTitle() + ".html")
    out = ""
    fileEnding = @editor.getTitle().split(".").pop()

```
